// <auto-generated />
using System;
using System.Collections.Generic;
using Infrastructure.Db.App;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Db.App.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260326071449_RemoveStatEventConstrains")]
    partial class RemoveStatEventConstrains
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Infrastructure.Db.App.Entities.BiomarkerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasComment("Идентификатор биомаркера");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description")
                        .HasComment("Техническое описание параметра");

                    b.Property<string>("DescriptionUser")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description_user")
                        .HasComment("Описание для пользователя");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key")
                        .HasComment("Уникальный ключ биомаркера");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name")
                        .HasComment("Название показателя");

                    b.Property<string>("Unit")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("unit")
                        .HasComment("Единица измерения");

                    b.HasKey("Id")
                        .HasName("pk_biomarkers");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("biomarkers", "biomarker");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.BiomarkerScaleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasComment("Идентификатор шкалы");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AgeFrom")
                        .HasColumnType("integer")
                        .HasColumnName("age_from")
                        .HasComment("Возраст от (лет)");

                    b.Property<int>("AgeTo")
                        .HasColumnType("integer")
                        .HasColumnName("age_to")
                        .HasComment("Возраст до (лет)");

                    b.Property<int>("BiomarkerId")
                        .HasColumnType("integer")
                        .HasColumnName("biomarker_id")
                        .HasComment("Идентификатор биомаркера");

                    b.Property<int>("GenderFrom")
                        .HasColumnType("integer")
                        .HasColumnName("gender_from")
                        .HasComment("Пол от (0=женщина, 1=мужчина)");

                    b.Property<int>("GenderTo")
                        .HasColumnType("integer")
                        .HasColumnName("gender_to")
                        .HasComment("Пол до (0=женщина, 1=мужчина)");

                    b.Property<bool>("RelativeToAge")
                        .HasColumnType("boolean")
                        .HasColumnName("relative_to_age")
                        .HasComment("Интерпретация относительно возраста пользователя");

                    b.Property<decimal>("ValueFrom")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("value_from")
                        .HasComment("Значение параметра от");

                    b.Property<decimal>("ValueTo")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("value_to")
                        .HasComment("Значение параметра до");

                    b.Property<decimal>("WeightFrom")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("weight_from")
                        .HasComment("Вес от (кг)");

                    b.Property<decimal>("WeightTo")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("weight_to")
                        .HasComment("Вес до (кг)");

                    b.HasKey("Id")
                        .HasName("pk_biomarker_scales");

                    b.HasIndex("BiomarkerId")
                        .HasDatabaseName("ix_biomarker_scales_biomarker_id");

                    b.ToTable("biomarker_scales", "biomarker");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.BiomarkerZoneEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasComment("Идентификатор зоны");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BiomarkerScaleId")
                        .HasColumnType("integer")
                        .HasColumnName("biomarker_scale_id")
                        .HasComment("Идентификатор шкалы");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("comment")
                        .HasComment("Комментарий к зоне");

                    b.Property<string>("CommentUser")
                        .HasColumnType("text")
                        .HasColumnName("comment_user")
                        .HasComment("Комментарий к зоне для пользователя");

                    b.Property<string>("FromToAlias")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("from_to_alias")
                        .HasComment("Человекочитаемый алиас диапазона (например, 60 - 100, < 50, 110 +)");

                    b.Property<string>("Rule")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("rule")
                        .HasComment("Правило интерпретации (для relativeToAge)");

                    b.Property<decimal?>("ValueFrom")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("value_from")
                        .HasComment("Начало диапазона значения");

                    b.Property<decimal?>("ValueTo")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("value_to")
                        .HasComment("Конец диапазона значения");

                    b.Property<string>("ZoneKey")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("zone_key")
                        .HasComment("Ключ зоны (red/yellow/green)");

                    b.HasKey("Id")
                        .HasName("pk_biomarker_zones");

                    b.HasIndex("BiomarkerScaleId")
                        .HasDatabaseName("ix_biomarker_zones_biomarker_scale_id");

                    b.ToTable("biomarker_zones", "biomarker");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.CategoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasComment("Идентификатор категории");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url")
                        .HasComment("URL изображения категории");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_id")
                        .HasComment("Идентификатор родительской категории");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title")
                        .HasComment("Название категории");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_categories_parent_id");

                    b.ToTable("categories", "x5");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.ExcludeProductEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Идентификатор продукта");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("product_name")
                        .HasComment("Наименование продукта");

                    b.HasKey("Id")
                        .HasName("pk_exclude_products");

                    b.ToTable("exclude_products", "app");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.LlmUsageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("ИД сущности.");

                    b.Property<int?>("CompletionTokens")
                        .HasColumnType("integer")
                        .HasColumnName("completion_tokens")
                        .HasComment("Число токенов на выходе");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("numeric")
                        .HasColumnName("cost")
                        .HasComment("Стоимость запроса (если провайдер вернул)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasComment("Когда сущность была создана.");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id")
                        .HasComment("Кто создал сущность.");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at")
                        .HasComment("Когда сущность была удалена.");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_id")
                        .HasComment("Кто удалил сущность.");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ms")
                        .HasComment("Длительность HTTP-запроса, мс");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message")
                        .HasComment("Сообщение об ошибке при неуспехе");

                    b.Property<string>("InputJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("input_json")
                        .HasComment("Входящий запрос к LLM в формате JSON");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean")
                        .HasColumnName("is_success")
                        .HasComment("Успешное завершение попытки (HTTP и разбор ответа)");

                    b.Property<string>("LlmModel")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("llm_model")
                        .HasComment("Имя модели LLM");

                    b.Property<string>("LlmRequestId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("llm_request_id")
                        .HasComment("Идентификатор запроса/ответа у провайдера LLM");

                    b.Property<string>("LlmResponse")
                        .HasColumnType("text")
                        .HasColumnName("llm_response")
                        .HasComment("Текст ответа ассистента или сырое тело ответа при сбое разбора");

                    b.Property<int?>("PromptTokens")
                        .HasColumnType("integer")
                        .HasColumnName("prompt_tokens")
                        .HasComment("Число токенов на входе");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasComment("Когда сущность была в последний раз обновлена.");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_id")
                        .HasComment("Кто обновил сущность.");

                    b.HasKey("Id")
                        .HasName("pk_llm_usages");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_llm_usages_created_by_id");

                    b.HasIndex("DeletedById")
                        .HasDatabaseName("ix_llm_usages_deleted_by_id");

                    b.HasIndex("UpdatedById")
                        .HasDatabaseName("ix_llm_usages_updated_by_id");

                    b.ToTable("llm_usages", "stat");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.ProductEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Идентификатор товара");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Allergens")
                        .HasColumnType("text")
                        .HasColumnName("allergens")
                        .HasComment("Аллергены");

                    b.Property<string>("Brand")
                        .HasColumnType("text")
                        .HasColumnName("brand")
                        .HasComment("Бренд");

                    b.Property<decimal?>("CarbsGPer100G")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("carbs_gper100_g")
                        .HasComment("Углеводы на 100 г");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id")
                        .HasComment("Идентификатор категории");

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasColumnName("country")
                        .HasComment("Страна производства");

                    b.Property<decimal?>("FatsGPer100G")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("fats_gper100_g")
                        .HasComment("Жиры на 100 г");

                    b.Property<string>("Features")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasComment("Характеристики товара");

                    b.Property<string>("FullIngrediants")
                        .HasColumnType("text")
                        .HasColumnName("full_ingrediants")
                        .HasComment("Полный состав");

                    b.Property<string>("Images")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("images")
                        .HasComment("URL изображений товара");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active")
                        .HasComment("Активен ли товар");

                    b.Property<bool?>("IsAdultContent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_adult_content")
                        .HasComment("Контент 18+");

                    b.Property<bool?>("IsAlcohol")
                        .HasColumnType("boolean")
                        .HasColumnName("is_alcohol")
                        .HasComment("Содержит алкоголь");

                    b.Property<bool?>("IsTobacco")
                        .HasColumnType("boolean")
                        .HasColumnName("is_tobacco")
                        .HasComment("Табачное изделие");

                    b.Property<decimal?>("KcalPer100G")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("kcal_per100_g")
                        .HasComment("Ккал на 100 г");

                    b.Property<string>("Labels")
                        .HasColumnType("text")
                        .HasColumnName("labels")
                        .HasComment("Метки товара");

                    b.Property<string>("MainIngrediants")
                        .HasColumnType("text")
                        .HasColumnName("main_ingrediants")
                        .HasComment("Основные ингредиенты");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("text")
                        .HasColumnName("manufacturer")
                        .HasComment("Производитель");

                    b.Property<string>("Plu")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("plu")
                        .HasComment("PLU код товара");

                    b.Property<int?>("Price")
                        .HasColumnType("integer")
                        .HasColumnName("price")
                        .HasComment("Цена в копейках");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority")
                        .HasComment("Приоритет сортировки");

                    b.Property<string>("ProductType")
                        .HasColumnType("text")
                        .HasColumnName("product_type")
                        .HasComment("Тип продукта");

                    b.Property<decimal?>("ProteinsGPer100G")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("proteins_gper100_g")
                        .HasComment("Белки на 100 г");

                    b.Property<int?>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating")
                        .HasComment("Рейтинг товара");

                    b.Property<int?>("ShelfLifeDays")
                        .HasColumnType("integer")
                        .HasColumnName("shelf_life_days")
                        .HasComment("Срок годности в днях");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title")
                        .HasComment("Название товара");

                    b.Property<string>("UnitName")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("unit_name")
                        .HasComment("Наименование единицы измерения");

                    b.Property<decimal?>("VolumeMl")
                        .HasPrecision(14, 3)
                        .HasColumnType("numeric(14,3)")
                        .HasColumnName("volume_ml")
                        .HasComment("Объём в мл");

                    b.Property<int?>("WeightG")
                        .HasColumnType("integer")
                        .HasColumnName("weight_g")
                        .HasComment("Вес в граммах");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_products_category_id");

                    b.HasIndex("Plu")
                        .IsUnique();

                    b.ToTable("products", "x5");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.StatEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("ИД сущности.");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasComment("Когда сущность была создана.");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id")
                        .HasComment("Кто создал сущность.");

                    b.Property<string>("Data")
                        .HasColumnType("text")
                        .HasColumnName("data")
                        .HasComment("Данные о событии");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at")
                        .HasComment("Когда сущность была удалена.");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_id")
                        .HasComment("Кто удалил сущность.");

                    b.Property<double?>("DurationSeconds")
                        .HasColumnType("double precision")
                        .HasColumnName("duration_seconds")
                        .HasComment("Длительность выполняемого события");

                    b.Property<long?>("SessionId")
                        .HasColumnType("bigint")
                        .HasColumnName("session_id")
                        .HasComment("Идентификатор сессии");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("type")
                        .HasComment("Тип события");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasComment("Когда сущность была в последний раз обновлена.");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_id")
                        .HasComment("Кто обновил сущность.");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasComment("Идентификатор пользователя");

                    b.HasKey("Id")
                        .HasName("pk_stat_events");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_stat_events_created_by_id");

                    b.HasIndex("DeletedById")
                        .HasDatabaseName("ix_stat_events_deleted_by_id");

                    b.HasIndex("UpdatedById")
                        .HasDatabaseName("ix_stat_events_updated_by_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_stat_events_user_id");

                    b.ToTable("stat_events", "stat");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_id");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", "app");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.UserExcludeProductEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("ИД сущности.");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasComment("Когда сущность была создана.");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id")
                        .HasComment("Кто создал сущность.");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at")
                        .HasComment("Когда сущность была удалена.");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_id")
                        .HasComment("Кто удалил сущность.");

                    b.Property<string>("ExcludeProduct")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("exclude_product")
                        .HasComment("Наименование продукта-исключения");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasComment("Когда сущность была в последний раз обновлена.");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_id")
                        .HasComment("Кто обновил сущность.");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasComment("Идентификатор пользователя");

                    b.HasKey("Id")
                        .HasName("pk_user_exclude_products");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_user_exclude_products_created_by_id");

                    b.HasIndex("DeletedById")
                        .HasDatabaseName("ix_user_exclude_products_deleted_by_id");

                    b.HasIndex("UpdatedById")
                        .HasDatabaseName("ix_user_exclude_products_updated_by_id");

                    b.HasIndex("UserId", "ExcludeProduct")
                        .IsUnique();

                    b.ToTable("user_exclude_products", "app");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.UserProfileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("ИД сущности.");

                    b.Property<int?>("Age")
                        .HasColumnType("integer")
                        .HasColumnName("age")
                        .HasComment("Возраст (лет)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasComment("Когда сущность была создана.");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id")
                        .HasComment("Кто создал сущность.");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at")
                        .HasComment("Когда сущность была удалена.");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_id")
                        .HasComment("Кто удалил сущность.");

                    b.Property<int?>("Gender")
                        .HasColumnType("integer")
                        .HasColumnName("gender")
                        .HasComment("Пол пользователя: 0 - муж, 1 - жен.");

                    b.PrimitiveCollection<List<string>>("Goals")
                        .HasColumnType("text[]")
                        .HasColumnName("goals")
                        .HasComment("Цели пользователя");

                    b.Property<int?>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height")
                        .HasComment("Рост в см.");

                    b.Property<int?>("SmokeStatus")
                        .HasColumnType("integer")
                        .HasColumnName("smoke_status")
                        .HasComment("Статус курения: 0 - не курит, 1 - курит");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasComment("Когда сущность была в последний раз обновлена.");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_id")
                        .HasComment("Кто обновил сущность.");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasComment("Идентификатор пользователя");

                    b.Property<int?>("Weight")
                        .HasColumnType("integer")
                        .HasColumnName("weight")
                        .HasComment("Вес в кг");

                    b.HasKey("Id")
                        .HasName("pk_user_profiles");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DeletedById");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("user_profiles", "app");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.UserRppgScanEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("ИД сущности.");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasComment("Когда сущность была создана.");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id")
                        .HasComment("Кто создал сущность.");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at")
                        .HasComment("Когда сущность была удалена.");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_id")
                        .HasComment("Кто удалил сущность.");

                    b.Property<string>("SdkResult")
                        .HasColumnType("text")
                        .HasColumnName("sdk_result");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("StatusMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("status_message");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasComment("Когда сущность была в последний раз обновлена.");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_id")
                        .HasComment("Кто обновил сущность.");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("WeekRationGenerationStatus")
                        .HasColumnType("integer")
                        .HasColumnName("week_ration_generation_status");

                    b.HasKey("Id")
                        .HasName("pk_user_rppg_scans");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_user_rppg_scans_created_by_id");

                    b.HasIndex("DeletedById")
                        .HasDatabaseName("ix_user_rppg_scans_deleted_by_id");

                    b.HasIndex("UpdatedById")
                        .HasDatabaseName("ix_user_rppg_scans_updated_by_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_rppg_scans_user_id");

                    b.ToTable("user_rppg_scans", "app");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.UserRppgScanResultItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("ИД сущности.");

                    b.Property<int?>("ConfidenceLevel")
                        .HasColumnType("integer")
                        .HasColumnName("confidence_level");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasComment("Когда сущность была создана.");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id")
                        .HasComment("Кто создал сущность.");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at")
                        .HasComment("Когда сущность была удалена.");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_id")
                        .HasComment("Кто удалил сущность.");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("key");

                    b.Property<Guid>("ScanId")
                        .HasColumnType("uuid")
                        .HasColumnName("scan_id");

                    b.Property<string>("Unit")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("unit");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasComment("Когда сущность была в последний раз обновлена.");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_id")
                        .HasComment("Кто обновил сущность.");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_user_rppg_scan_result_items");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_user_rppg_scan_result_items_created_by_id");

                    b.HasIndex("DeletedById")
                        .HasDatabaseName("ix_user_rppg_scan_result_items_deleted_by_id");

                    b.HasIndex("ScanId")
                        .HasDatabaseName("ix_user_rppg_scan_result_items_scan_id");

                    b.HasIndex("UpdatedById")
                        .HasDatabaseName("ix_user_rppg_scan_result_items_updated_by_id");

                    b.ToTable("user_rppg_scan_result_items", "app");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.WeekRationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("ИД сущности.");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasComment("Когда сущность была создана.");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id")
                        .HasComment("Кто создал сущность.");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at")
                        .HasComment("Когда сущность была удалена.");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_id")
                        .HasComment("Кто удалил сущность.");

                    b.Property<Guid>("RppgScanId")
                        .HasColumnType("uuid")
                        .HasColumnName("rppg_scan_id")
                        .HasComment("Идентификатор скана RPPG");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasComment("Когда сущность была в последний раз обновлена.");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_id")
                        .HasComment("Кто обновил сущность.");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasComment("Идентификатор пользователя");

                    b.HasKey("Id")
                        .HasName("pk_week_rations");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_week_rations_created_by_id");

                    b.HasIndex("DeletedById")
                        .HasDatabaseName("ix_week_rations_deleted_by_id");

                    b.HasIndex("RppgScanId")
                        .HasDatabaseName("ix_week_rations_rppg_scan_id");

                    b.HasIndex("UpdatedById")
                        .HasDatabaseName("ix_week_rations_updated_by_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_week_rations_user_id");

                    b.ToTable("week_rations", "app");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.WeekRationItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("ИД сущности.");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasComment("Когда сущность была создана.");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id")
                        .HasComment("Кто создал сущность.");

                    b.Property<int>("Day")
                        .HasColumnType("integer")
                        .HasColumnName("day")
                        .HasComment("День недели (1–7)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at")
                        .HasComment("Когда сущность была удалена.");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_id")
                        .HasComment("Кто удалил сущность.");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id")
                        .HasComment("Идентификатор товара из каталога X5");

                    b.Property<string>("Reason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reason")
                        .HasComment("Краткая причина включения товара");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type")
                        .HasComment("Тип приёма пищи");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasComment("Когда сущность была в последний раз обновлена.");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_id")
                        .HasComment("Кто обновил сущность.");

                    b.Property<Guid>("WeekRationId")
                        .HasColumnType("uuid")
                        .HasColumnName("week_ration_id")
                        .HasComment("Идентификатор рациона");

                    b.Property<int>("Weigth")
                        .HasColumnType("integer")
                        .HasColumnName("weigth")
                        .HasComment("Вес порции, г");

                    b.HasKey("Id")
                        .HasName("pk_week_ration_items");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_week_ration_items_created_by_id");

                    b.HasIndex("DeletedById")
                        .HasDatabaseName("ix_week_ration_items_deleted_by_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_week_ration_items_product_id");

                    b.HasIndex("UpdatedById")
                        .HasDatabaseName("ix_week_ration_items_updated_by_id");

                    b.HasIndex("WeekRationId")
                        .HasDatabaseName("ix_week_ration_items_week_ration_id");

                    b.ToTable("week_ration_items", "app");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.WeekRationItemReplaceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("ИД сущности.");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasComment("Когда сущность была создана.");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id")
                        .HasComment("Кто создал сущность.");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at")
                        .HasComment("Когда сущность была удалена.");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_id")
                        .HasComment("Кто удалил сущность.");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id")
                        .HasComment("Идентификатор товара-замены из каталога X5");

                    b.Property<string>("Reason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reason")
                        .HasComment("Пояснение к замене");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasComment("Когда сущность была в последний раз обновлена.");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_id")
                        .HasComment("Кто обновил сущность.");

                    b.Property<Guid>("WeekRationItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("week_ration_item_id")
                        .HasComment("Идентификатор позиции рациона");

                    b.Property<int>("Weight")
                        .HasColumnType("integer")
                        .HasColumnName("weight")
                        .HasComment("Вес порции замены, г");

                    b.HasKey("Id")
                        .HasName("pk_week_ration_item_replaces");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_week_ration_item_replaces_created_by_id");

                    b.HasIndex("DeletedById")
                        .HasDatabaseName("ix_week_ration_item_replaces_deleted_by_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_week_ration_item_replaces_product_id");

                    b.HasIndex("UpdatedById")
                        .HasDatabaseName("ix_week_ration_item_replaces_updated_by_id");

                    b.HasIndex("WeekRationItemId")
                        .HasDatabaseName("ix_week_ration_item_replaces_week_ration_item_id");

                    b.ToTable("week_ration_item_replaces", "app");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.BiomarkerScaleEntity", b =>
                {
                    b.HasOne("Infrastructure.Db.App.Entities.BiomarkerEntity", "Biomarker")
                        .WithMany("Scales")
                        .HasForeignKey("BiomarkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_biomarker_scales_biomarkers_biomarker_id");

                    b.Navigation("Biomarker");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.BiomarkerZoneEntity", b =>
                {
                    b.HasOne("Infrastructure.Db.App.Entities.BiomarkerScaleEntity", "BiomarkerScale")
                        .WithMany("Zones")
                        .HasForeignKey("BiomarkerScaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_biomarker_zones_biomarker_scales_biomarker_scale_id");

                    b.Navigation("BiomarkerScale");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.CategoryEntity", b =>
                {
                    b.HasOne("Infrastructure.Db.App.Entities.CategoryEntity", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_categories_categories_parent_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.LlmUsageEntity", b =>
                {
                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .HasConstraintName("fk_llm_usages_users_created_by_id");

                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .HasConstraintName("fk_llm_usages_users_deleted_by_id");

                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .HasConstraintName("fk_llm_usages_users_updated_by_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.ProductEntity", b =>
                {
                    b.HasOne("Infrastructure.Db.App.Entities.CategoryEntity", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_products_categories_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.StatEventEntity", b =>
                {
                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .HasConstraintName("fk_stat_events_users_created_by_id");

                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .HasConstraintName("fk_stat_events_users_deleted_by_id");

                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .HasConstraintName("fk_stat_events_users_updated_by_id");

                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_stat_events_users_user_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("UpdatedBy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.UserExcludeProductEntity", b =>
                {
                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .HasConstraintName("fk_user_exclude_products_users_created_by_id");

                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .HasConstraintName("fk_user_exclude_products_users_deleted_by_id");

                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .HasConstraintName("fk_user_exclude_products_users_updated_by_id");

                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_exclude_products_users_user_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("UpdatedBy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.UserProfileEntity", b =>
                {
                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById");

                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");

                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "User")
                        .WithOne("Profile")
                        .HasForeignKey("Infrastructure.Db.App.Entities.UserProfileEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("UpdatedBy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.UserRppgScanEntity", b =>
                {
                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .HasConstraintName("fk_user_rppg_scans_users_created_by_id");

                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .HasConstraintName("fk_user_rppg_scans_users_deleted_by_id");

                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .HasConstraintName("fk_user_rppg_scans_users_updated_by_id");

                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_rppg_scans_users_user_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("UpdatedBy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.UserRppgScanResultItemEntity", b =>
                {
                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .HasConstraintName("fk_user_rppg_scan_result_items_users_created_by_id");

                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .HasConstraintName("fk_user_rppg_scan_result_items_users_deleted_by_id");

                    b.HasOne("Infrastructure.Db.App.Entities.UserRppgScanEntity", "Scan")
                        .WithMany("ResultItems")
                        .HasForeignKey("ScanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_rppg_scan_result_items_user_rppg_scans_scan_id");

                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .HasConstraintName("fk_user_rppg_scan_result_items_users_updated_by_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("Scan");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.WeekRationEntity", b =>
                {
                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .HasConstraintName("fk_week_rations_users_created_by_id");

                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .HasConstraintName("fk_week_rations_users_deleted_by_id");

                    b.HasOne("Infrastructure.Db.App.Entities.UserRppgScanEntity", "RppgScan")
                        .WithMany()
                        .HasForeignKey("RppgScanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_week_rations_user_rppg_scans_rppg_scan_id");

                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .HasConstraintName("fk_week_rations_users_updated_by_id");

                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_week_rations_users_user_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("RppgScan");

                    b.Navigation("UpdatedBy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.WeekRationItemEntity", b =>
                {
                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .HasConstraintName("fk_week_ration_items_users_created_by_id");

                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .HasConstraintName("fk_week_ration_items_users_deleted_by_id");

                    b.HasOne("Infrastructure.Db.App.Entities.ProductEntity", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_week_ration_items_products_product_id");

                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .HasConstraintName("fk_week_ration_items_users_updated_by_id");

                    b.HasOne("Infrastructure.Db.App.Entities.WeekRationEntity", "WeekRation")
                        .WithMany("Items")
                        .HasForeignKey("WeekRationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_week_ration_items_week_rations_week_ration_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("Product");

                    b.Navigation("UpdatedBy");

                    b.Navigation("WeekRation");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.WeekRationItemReplaceEntity", b =>
                {
                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .HasConstraintName("fk_week_ration_item_replaces_users_created_by_id");

                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .HasConstraintName("fk_week_ration_item_replaces_users_deleted_by_id");

                    b.HasOne("Infrastructure.Db.App.Entities.ProductEntity", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_week_ration_item_replaces_products_product_id");

                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .HasConstraintName("fk_week_ration_item_replaces_users_updated_by_id");

                    b.HasOne("Infrastructure.Db.App.Entities.WeekRationItemEntity", "WeekRationItem")
                        .WithMany("Replaces")
                        .HasForeignKey("WeekRationItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_week_ration_item_replaces_week_ration_items_week_ration_ite~");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("Product");

                    b.Navigation("UpdatedBy");

                    b.Navigation("WeekRationItem");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.BiomarkerEntity", b =>
                {
                    b.Navigation("Scales");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.BiomarkerScaleEntity", b =>
                {
                    b.Navigation("Zones");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.CategoryEntity", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.UserEntity", b =>
                {
                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.UserRppgScanEntity", b =>
                {
                    b.Navigation("ResultItems");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.WeekRationEntity", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.WeekRationItemEntity", b =>
                {
                    b.Navigation("Replaces");
                });
#pragma warning restore 612, 618
        }
    }
}
