// <auto-generated />
using System;
using System.Collections.Generic;
using Infrastructure.Db.App;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Db.App.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260310154613_Changes2")]
    partial class Changes2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Infrastructure.Db.App.Entities.StatEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("ИД сущности.");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasComment("Когда сущность была создана.");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id")
                        .HasComment("Кто создал сущность.");

                    b.Property<string>("Data")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("data")
                        .HasComment("Данные о событии");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at")
                        .HasComment("Когда сущность была удалена.");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_id")
                        .HasComment("Кто удалил сущность.");

                    b.Property<double?>("DurationSeconds")
                        .HasColumnType("double precision")
                        .HasColumnName("duration_seconds")
                        .HasComment("Длительность выполняемого события");

                    b.Property<long?>("SessionId")
                        .HasColumnType("bigint")
                        .HasColumnName("session_id")
                        .HasComment("Идентификатор сессии");

                    b.Property<string>("Type")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type")
                        .HasComment("Тип события");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasComment("Когда сущность была в последний раз обновлена.");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_id")
                        .HasComment("Кто обновил сущность.");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasComment("Идентификатор пользователя");

                    b.HasKey("Id")
                        .HasName("pk_stat_events");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_stat_events_created_by_id");

                    b.HasIndex("DeletedById")
                        .HasDatabaseName("ix_stat_events_deleted_by_id");

                    b.HasIndex("UpdatedById")
                        .HasDatabaseName("ix_stat_events_updated_by_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_stat_events_user_id");

                    b.ToTable("stat_events", "stat");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_id");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", "app");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.UserProfileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("ИД сущности.");

                    b.Property<int?>("Age")
                        .HasColumnType("integer")
                        .HasColumnName("age")
                        .HasComment("Возраст (лет)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasComment("Когда сущность была создана.");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id")
                        .HasComment("Кто создал сущность.");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at")
                        .HasComment("Когда сущность была удалена.");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_id")
                        .HasComment("Кто удалил сущность.");

                    b.Property<int?>("Gender")
                        .HasColumnType("integer")
                        .HasColumnName("gender")
                        .HasComment("Пол пользователя: 0 - муж, 1 - жен.");

                    b.PrimitiveCollection<List<string>>("Goals")
                        .HasColumnType("text[]")
                        .HasColumnName("goals")
                        .HasComment("Цели пользователя");

                    b.Property<int?>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height")
                        .HasComment("Рост в см.");

                    b.Property<int?>("SmokeStatus")
                        .HasColumnType("integer")
                        .HasColumnName("smoke_status")
                        .HasComment("Статус курения: 0 - не курит, 1 - курит");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasComment("Когда сущность была в последний раз обновлена.");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_id")
                        .HasComment("Кто обновил сущность.");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasComment("Идентификатор пользователя");

                    b.Property<int?>("Weight")
                        .HasColumnType("integer")
                        .HasColumnName("weight")
                        .HasComment("Вес в кг");

                    b.HasKey("Id")
                        .HasName("pk_user_profiles");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DeletedById");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("user_profiles", "app");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.UserRppgScanEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("ИД сущности.");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasComment("Когда сущность была создана.");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id")
                        .HasComment("Кто создал сущность.");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at")
                        .HasComment("Когда сущность была удалена.");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_id")
                        .HasComment("Кто удалил сущность.");

                    b.Property<string>("SdkResult")
                        .HasColumnType("text")
                        .HasColumnName("sdk_result");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasComment("Когда сущность была в последний раз обновлена.");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_id")
                        .HasComment("Кто обновил сущность.");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_rppg_scans");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_user_rppg_scans_created_by_id");

                    b.HasIndex("DeletedById")
                        .HasDatabaseName("ix_user_rppg_scans_deleted_by_id");

                    b.HasIndex("UpdatedById")
                        .HasDatabaseName("ix_user_rppg_scans_updated_by_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_rppg_scans_user_id");

                    b.ToTable("user_rppg_scans", "app");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.UserRppgScanResultItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("ИД сущности.");

                    b.Property<int?>("ConfidenceLevel")
                        .HasColumnType("integer")
                        .HasColumnName("confidence_level");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasComment("Когда сущность была создана.");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id")
                        .HasComment("Кто создал сущность.");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at")
                        .HasComment("Когда сущность была удалена.");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_id")
                        .HasComment("Кто удалил сущность.");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("key");

                    b.Property<Guid>("ScanId")
                        .HasColumnType("uuid")
                        .HasColumnName("scan_id");

                    b.Property<string>("Unit")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("unit");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasComment("Когда сущность была в последний раз обновлена.");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_id")
                        .HasComment("Кто обновил сущность.");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_user_rppg_scan_result_items");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_user_rppg_scan_result_items_created_by_id");

                    b.HasIndex("DeletedById")
                        .HasDatabaseName("ix_user_rppg_scan_result_items_deleted_by_id");

                    b.HasIndex("ScanId")
                        .HasDatabaseName("ix_user_rppg_scan_result_items_scan_id");

                    b.HasIndex("UpdatedById")
                        .HasDatabaseName("ix_user_rppg_scan_result_items_updated_by_id");

                    b.ToTable("user_rppg_scan_result_items", "app");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.StatEventEntity", b =>
                {
                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .HasConstraintName("fk_stat_events_users_created_by_id");

                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .HasConstraintName("fk_stat_events_users_deleted_by_id");

                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .HasConstraintName("fk_stat_events_users_updated_by_id");

                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_stat_events_users_user_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("UpdatedBy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.UserProfileEntity", b =>
                {
                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById");

                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");

                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "User")
                        .WithOne("Profile")
                        .HasForeignKey("Infrastructure.Db.App.Entities.UserProfileEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("UpdatedBy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.UserRppgScanEntity", b =>
                {
                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .HasConstraintName("fk_user_rppg_scans_users_created_by_id");

                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .HasConstraintName("fk_user_rppg_scans_users_deleted_by_id");

                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .HasConstraintName("fk_user_rppg_scans_users_updated_by_id");

                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_rppg_scans_users_user_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("UpdatedBy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.UserRppgScanResultItemEntity", b =>
                {
                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .HasConstraintName("fk_user_rppg_scan_result_items_users_created_by_id");

                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .HasConstraintName("fk_user_rppg_scan_result_items_users_deleted_by_id");

                    b.HasOne("Infrastructure.Db.App.Entities.UserRppgScanEntity", "Scan")
                        .WithMany("ResultItems")
                        .HasForeignKey("ScanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_rppg_scan_result_items_user_rppg_scans_scan_id");

                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .HasConstraintName("fk_user_rppg_scan_result_items_users_updated_by_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("Scan");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.UserEntity", b =>
                {
                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.UserRppgScanEntity", b =>
                {
                    b.Navigation("ResultItems");
                });
#pragma warning restore 612, 618
        }
    }
}
